import { create } from "zustand";

export type ChartType = "candles" | "heikin_ashi" | "line" | "line_with_markers" | "area" | "bars";
export interface IndicatorState { ema9:boolean; ema21:boolean; ema50:boolean; ema200:boolean; vwap:boolean; }
export interface OHLCBar { time:number; open:number; high:number; low:number; close:number; volume:number; }
export interface CrosshairInfo { time:number|null; open:number|null; high:number|null; low:number|null; close:number|null; volume:number|null; }
interface ChartStoreState { symbol:string; interval:string; chartType:ChartType; indicators:IndicatorState; livePrice:number|null; liveOpen:number|null; crosshairInfo:CrosshairInfo; barsLoaded:boolean; mobileChartFullscreen:boolean; dashboardSheetOpen:boolean; setSymbol:(s:string)=>void; setInterval:(i:string)=>void; setChartType:(t:ChartType)=>void; setIndicator:(key:keyof IndicatorState,val:boolean)=>void; setLivePrice:(p:number|null)=>void; setLiveOpen:(p:number|null)=>void; setCrosshair:(info:CrosshairInfo)=>void; setBarsLoaded:(v:boolean)=>void; setMobileChartFullscreen:(v:boolean)=>void; setDashboardSheetOpen:(v:boolean)=>void; dashboardAlertsOpen:boolean; setDashboardAlertsOpen:(v:boolean)=>void; dashboardMarketsOpen:boolean; setDashboardMarketsOpen:(v:boolean)=>void; }
const EMPTY={ema9:false,ema21:false,ema50:false,ema200:false,vwap:false};
function hasAppliedIndicators():boolean{try{const applied=JSON.parse(localStorage.getItem("tj_applied_indicators_v2")??"null") as Array<{type?:string}>|null;return Array.isArray(applied)&&applied.some(i=>i?.type&&i.type!=="CUSTOM")}catch{return false}}
const loadIndicators=():IndicatorState=>{try{if(hasAppliedIndicators()){localStorage.setItem("tv_indicators",JSON.stringify(EMPTY));return EMPTY}const s=localStorage.getItem("tv_indicators");if(s)return {...EMPTY,...JSON.parse(s)};}catch{}return EMPTY};
const _initSymbol=(typeof localStorage!=="undefined"?localStorage.getItem("tv_symbol"):null)??"BTCUSD";
const _initInterval=(typeof localStorage!=="undefined"?localStorage.getItem("tv_interval"):null)??"60";
if(typeof localStorage!=="undefined"){localStorage.setItem("tv_symbol",_initSymbol);localStorage.setItem("tv_interval",_initInterval)}
export const useChartStore=create<ChartStoreState>((set,get)=>({
 symbol:_initSymbol,interval:_initInterval,chartType:(typeof localStorage!=="undefined"?localStorage.getItem("tv_chartType") as ChartType:null)??"candles",indicators:loadIndicators(),livePrice:null,liveOpen:null,crosshairInfo:{time:null,open:null,high:null,low:null,close:null,volume:null},barsLoaded:false,mobileChartFullscreen:false,dashboardSheetOpen:false,dashboardAlertsOpen:false,dashboardMarketsOpen:false,
 setSymbol:s=>{localStorage.setItem("tv_symbol",s);set({symbol:s,barsLoaded:false})},setInterval:i=>{localStorage.setItem("tv_interval",i);set({interval:i,barsLoaded:false})},setChartType:t=>{localStorage.setItem("tv_chartType",t);set({chartType:t})},setIndicator:(key,val)=>{if(hasAppliedIndicators()){const empty={...EMPTY};localStorage.setItem("tv_indicators",JSON.stringify(empty));set({indicators:empty});return}const next={...get().indicators,[key]:val};localStorage.setItem("tv_indicators",JSON.stringify(next));set({indicators:next})},setLivePrice:p=>set({livePrice:p}),setLiveOpen:p=>set({liveOpen:p}),setCrosshair:crosshairInfo=>set({crosshairInfo}),setBarsLoaded:barsLoaded=>set({barsLoaded}),setMobileChartFullscreen:v=>set({mobileChartFullscreen:v}),setDashboardSheetOpen:v=>set({dashboardSheetOpen:v}),setDashboardAlertsOpen:v=>set({dashboardAlertsOpen:v}),setDashboardMarketsOpen:v=>set({dashboardMarketsOpen:v})
}));
