import type { OHLCBar } from "@/store/chartStore";

export type PineResultType="EMA"|"SMA"|"RSI"|"VWAP"|"WAVETREND"|"SMC_FULL"|"SMC_STRUCTURE"|"SMC_FVG"|"SMC_OB"|"SMC_LIQUIDITY"|"UNKNOWN";
export interface PinePlot{time:number;value:number}
export interface PineSeries{id:string;name:string;plots:PinePlot[];color:string;lineWidth?:number;style:"line"|"area"|"histogram";areaTopColor?:string;areaBottomColor?:string}
export interface PineHLine{price:number;color:string;lineStyle?:"solid"|"dashed"|"dotted";label?:string}
export interface PineZone{kind:"fvg_bull"|"fvg_bear"|"ob_bull"|"ob_bear";top:number;bottom:number;startTime:number;endTime:number;label?:string}
export interface PineLevel{kind:"bos_bull"|"bos_bear"|"choch_bull"|"choch_bear"|"liq_high"|"liq_low";price:number;time:number;label:string}
export interface ParsedPineResult{type:PineResultType;overlay:boolean;period?:number;plots:PinePlot[];multiSeries:PineSeries[];hlines:PineHLine[];zones:PineZone[];levels:PineLevel[]}

export function parsePineScript(code:string):{type:PineResultType;period?:number;overlay:boolean}{
 const l=code.toLowerCase();
 if(/wavetrend|wt[\s_]?lb|wt1|wt2|tci\s*=|hlc3|ci\s*=\s*\(ap|channel.?length/.test(l))return{type:"WAVETREND",overlay:false};
 const smc=/\b(bos|choch|ob|order[\s._-]?block|fvg|fair[\s._-]?value|liquidity|smc|smart[\s._-]?money|imbalance|supply|demand)\b/;
 if(smc.test(l)){const a=/\b(bos|choch|structure)\b/.test(l),b=/\b(fvg|fair[\s._-]?value|imbalance)\b/.test(l),c=/\b(ob|order[\s._-]?block|supply|demand)\b/.test(l),d=/\b(liquidity|equal[\s._-]?(high|low))\b/.test(l);if([a,b,c,d].filter(Boolean).length>=2)return{type:"SMC_FULL",overlay:true};if(b)return{type:"SMC_FVG",overlay:true};if(a)return{type:"SMC_STRUCTURE",overlay:true};if(c)return{type:"SMC_OB",overlay:true};return{type:"SMC_LIQUIDITY",overlay:true}}
 const e=code.match(/ta\.ema\s*\(\s*\w+\s*,\s*(\d+)\s*\)/);if(e)return{type:"EMA",period:+e[1],overlay:true};
 const s=code.match(/ta\.sma\s*\(\s*\w+\s*,\s*(\d+)\s*\)/);if(s)return{type:"SMA",period:+s[1],overlay:true};
 const r=code.match(/ta\.rsi\s*\(\s*\w+\s*,\s*(\d+)\s*\)/);if(r)return{type:"RSI",period:+r[1],overlay:!/overlay\s*=\s*false/.test(l)};
 if(/ta\.vwap/.test(code))return{type:"VWAP",overlay:true};return{type:"UNKNOWN",overlay:true};
}
function ema(v:number[],p:number){const o:number[]=[];if(!v.length)return o;const k=2/(p+1);let e=v[0];o.push(e);for(let i=1;i<v.length;i++){e=v[i]*k+e*(1-k);o.push(e)}return o}
function sma(v:number[],p:number){return v.map((_,i)=>i<p-1?0:v.slice(i-p+1,i+1).reduce((a,b)=>a+b,0)/p)}
export function calcEMA(v:number[],p:number):(number|null)[]{if(!v.length)return[];const k=2/(Math.max(1,Math.floor(p)||1)+1),o:(number|null)[]=new Array(v.length);let e=v[0];o[0]=e;for(let i=1;i<v.length;i++){e=v[i]*k+e*(1-k);o[i]=e}return o}
function calcSMA(v:number[],p:number):(number|null)[]{return v.map((_,i)=>i<p-1?null:v.slice(i-p+1,i+1).reduce((a,b)=>a+b,0)/p)}
function calcVWAP(b:OHLCBar[]):(number|null)[]{let pv=0,vol=0;return b.map(x=>{const tp=(x.high+x.low+x.close)/3;pv+=tp*x.volume;vol+=x.volume;return vol?pv/vol:null})}
function calcRSI(v:number[],p:number):(number|null)[]{const o:(number|null)[]=new Array(p).fill(null);if(v.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>=0)g+=d;else l-=d}g/=p;l/=p;o.push(l===0?100:100-100/(1+g/l));for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];g=(g*(p-1)+(d>0?d:0))/p;l=(l*(p-1)+(d<0?-d:0))/p;o.push(l===0?100:100-100/(1+g/l))}return o}
function extract(code:string,names:string[],def:number){for(const n of names){const m=code.match(new RegExp(`${n}\\s*=\\s*input\\.int\\s*\\(\\s*(-?\\d+)`,'i'))??code.match(new RegExp(`${n}\\s*=\\s*(-?\\d+)`,'i'));if(m)return+m[1]}return def}
function calcWT(b:OHLCBar[],n1=10,n2=21,sp=4){const ap=b.map(x=>(x.high+x.low+x.close)/3),esa=ema(ap,n1),d=ema(ap.map((v,i)=>Math.abs(v-esa[i])),n1),ci=ap.map((v,i)=>d[i]<1e-10?0:(v-esa[i])/(.015*d[i])),wt1=ema(ci,n2),wt2=sma(wt1,sp);return{wt1,wt2,diff:wt1.map((v,i)=>v-wt2[i])}}
function fvg(b:OHLCBar[]){const z:PineZone[]=[];const a=b.slice(-200);for(let i=2;i<a.length;i++){const x=a[i-2],y=a[i];if(x.high<y.low)z.push({kind:"fvg_bull",top:y.low,bottom:x.high,startTime:x.time,endTime:y.time,label:"FVG"});else if(x.low>y.high)z.push({kind:"fvg_bear",top:x.low,bottom:y.high,startTime:x.time,endTime:y.time,label:"FVG"})}return z.slice(-8)}
function ob(b:OHLCBar[]){const z:PineZone[]=[];const a=b.slice(-150);for(let i=0;i<a.length-4;i++){const x=a[i];if(x.close<x.open&&[1,2,3].every(j=>a[i+j].close>a[i+j].open))z.push({kind:"ob_bull",top:x.open,bottom:x.close,startTime:x.time,endTime:a[i+3].time,label:"OB"});if(x.close>x.open&&[1,2,3].every(j=>a[i+j].close<a[i+j].open))z.push({kind:"ob_bear",top:x.close,bottom:x.open,startTime:x.time,endTime:a[i+3].time,label:"OB"})}return z.slice(-6)}
function structure(b:OHLCBar[]){const a=b.slice(-120),hi:{price:number;time:number}[]=[],lo:{price:number;time:number}[]=[];for(let i=2;i<a.length-2;i++){const x=a[i];if(x.high>a[i-1].high&&x.high>a[i-2].high&&x.high>a[i+1].high&&x.high>a[i+2].high)hi.push({price:x.high,time:x.time});if(x.low<a[i-1].low&&x.low<a[i-2].low&&x.low<a[i+1].low&&x.low<a[i+2].low)lo.push({price:x.low,time:x.time})}const r:PineLevel[]=[];for(let i=1;i<hi.length;i++)if(hi[i].price>hi[i-1].price)r.push({kind:"bos_bull",price:hi[i-1].price,time:hi[i].time,label:"BOS"});for(let i=1;i<lo.length;i++)if(lo[i].price<lo[i-1].price)r.push({kind:"bos_bear",price:lo[i-1].price,time:lo[i].time,label:"BOS"});if(hi.length>=2&&lo.length>=2){const h=hi.at(-1)!,ph=hi.at(-2)!,l=lo.at(-1)!,pl=lo.at(-2)!;if(h.price<ph.price&&l.price<pl.price)r.push({kind:"choch_bear",price:h.price,time:h.time,label:"CHoCH"});if(h.price>ph.price&&l.price>pl.price)r.push({kind:"choch_bull",price:l.price,time:l.time,label:"CHoCH"})}return r.slice(-10)}
function liquidity(b:OHLCBar[]){const a=b.slice(-150),r:PineLevel[]=[];for(let i=0;i<a.length-5;i++)for(let j=i+3;j<a.length;j++)if(Math.abs(a[i].high-a[j].high)/a[i].high<.002){r.push({kind:"liq_high",price:(a[i].high+a[j].high)/2,time:a[j].time,label:"EQH"});break}for(let i=0;i<a.length-5;i++)for(let j=i+3;j<a.length;j++)if(Math.abs(a[i].low-a[j].low)/a[i].low<.002){r.push({kind:"liq_low",price:(a[i].low+a[j].low)/2,time:a[j].time,label:"EQL"});break}return r.slice(-8)}
export function computeCustomIndicator(parsed:{type:PineResultType;period?:number;overlay:boolean},bars:OHLCBar[],color:string,pineCode=""):ParsedPineResult{const base:ParsedPineResult={type:parsed.type,overlay:parsed.overlay,period:parsed.period,plots:[],multiSeries:[],hlines:[],zones:[],levels:[]};if(bars.length<5)return base;const c=bars.map(x=>x.close);switch(parsed.type){case"EMA":{const v=calcEMA(c,parsed.period??9);base.plots=bars.map((x,i)=>({time:x.time,value:v[i]!}));break}case"SMA":{const v=calcSMA(c,parsed.period??20);base.plots=bars.flatMap((x,i)=>v[i]!=null?[{time:x.time,value:v[i]!}]:[]);break}case"VWAP":{const v=calcVWAP(bars);base.plots=bars.flatMap((x,i)=>v[i]!=null?[{time:x.time,value:v[i]!}]:[]);break}case"RSI":{const v=calcRSI(c,parsed.period??14),q=c.slice(-100),mn=Math.min(...q),mx=Math.max(...q),rg=mx-mn||1;base.plots=bars.flatMap((x,i)=>v[i]!=null?[{time:x.time,value:mn+(v[i]!/100)*rg}]:[]);break}case"WAVETREND":{const n1=extract(pineCode,["n1","channel_length","channelLength"],10),n2=extract(pineCode,["n2","average_length","averageLength"],21),{wt1,wt2,diff}=calcWT(bars,n1,n2);base.multiSeries=[{id:"wt_diff",name:"WT Diff",plots:bars.map((x,i)=>({time:x.time,value:diff[i]})),color:"rgba(59,130,246,.25)",style:"area",areaTopColor:"rgba(59,130,246,.3)",areaBottomColor:"rgba(59,130,246,.05)"},{id:"wt2",name:"WT2",plots:bars.map((x,i)=>({time:x.time,value:wt2[i]})),color:"#ef4444",style:"line",lineWidth:1},{id:"wt1",name:"WT1",plots:bars.map((x,i)=>({time:x.time,value:wt1[i]})),color:"#22c55e",style:"line",lineWidth:1}];base.hlines=[{price:60,color:"rgba(239,68,68,.7)"},{price:53,color:"rgba(239,68,68,.45)",lineStyle:"dashed"},{price:0,color:"rgba(156,163,175,.5)"},{price:-53,color:"rgba(34,197,94,.45)",lineStyle:"dashed"},{price:-60,color:"rgba(34,197,94,.7)}];break}case"SMC_FULL":case"SMC_STRUCTURE":base.levels=structure(bars);if(parsed.type==="SMC_FULL"){base.zones=[...fvg(bars),...ob(bars)];base.levels=[...base.levels,...liquidity(bars)]}break;case"SMC_FVG":base.zones=fvg(bars);break;case"SMC_OB":base.zones=ob(bars);break;case"SMC_LIQUIDITY":base.levels=liquidity(bars);break;default:break}void color;return base}
